### PR TITLE
BloggerApp: Controller Specs

### PR DESCRIPTION
**Pull request by BenjaminSemah**
### In this branch, I have worked on the following;
✅ added RSpec as a gem to the `BloggerApp` project,
✅ added request specs for all actions in the `UsersController`,
✅ added request specs for all actions in the `PostsController`,
✅ fixed linters errors.

### CODE REVIEW

**Review by Gambit142 — APPROVED** [review]
Hi @BenjaminSemah 👋, 

Good job so far!

## Highlights

- Installed `rspec-rails` gem ✔️ 
- Wrote `request spec` tests for `Users` controller ✔️ 
-  Wrote `request spec` tests for `Posts` controller ✔️

However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- Kindly populate your `README.md` file with the appropriate sections. You can use this [Microverse Template](https://github.com/microverseinc/readme-template/blob/master/README.md). Please, ensure that you include the section for setting up this project on a local machine along with instructions on how to install dependencies. 👍 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by BenjaminSemah** [comment]
Thank you @Gambit142

**Comment by Gambit142** [comment]
Hi @BenjaminSemah, I didn't approve this pull request and I can see that you have merged it. Your dashboard should show required changes, kindly make the changes I suggested. 👍

**Comment by BenjaminSemah** [comment]
@Gambit142 Yeah. It was a mistake. I would update and `ReadMe` as requested.

**Pull request merged**
